"use client";

import { useEffect, useRef, useState } from "react";
import { Rocket, Building2, Target, Brain, Code } from "lucide-react";
import StarBackground from "./StarBackground";

interface AudienceCardProps {
  icon: React.ReactNode;
  title: string;
  description: string;
  index: number;
}

function AudienceCard({ icon, title, description, index }: AudienceCardProps) {
  const cardRef = useRef<HTMLDivElement>(null);
  const [isVisible, setIsVisible] = useState(false);

  useEffect(() => {
    const observer = new IntersectionObserver(
      ([entry]) => {
        if (entry.isIntersecting) {
          setTimeout(() => setIsVisible(true), index * 100);
        }
      },
      { threshold: 0.2 }
    );

    if (cardRef.current) {
      observer.observe(cardRef.current);
    }

    return () => observer.disconnect();
  }, [index]);

  return (
    <div 
      ref={cardRef}
      className={`group relative ${
        isVisible ? "opacity-100 translate-y-0" : "opacity-0 translate-y-8"
      } transition-all duration-700 ease-out`}
    >
      <div className="relative h-full bg-gradient-to-br from-white/[0.03] to-transparent border border-white/10 rounded-2xl p-6 hover:border-paraflow-green/30 hover:bg-white/[0.04] transition-all duration-500 cursor-pointer overflow-hidden">
        {/* 背景光效 */}
        <div className="absolute inset-0 opacity-0 group-hover:opacity-100 transition-opacity duration-700">
          <div 
            className="absolute -top-20 -right-20 w-40 h-40 rounded-full"
            style={{
              background: "radial-gradient(circle, rgba(0, 192, 92, 0.15) 0%, transparent 70%)",
              filter: "blur(30px)",
            }}
          />
        </div>
        
        {/* 图标 */}
        <div className="w-12 h-12 rounded-xl bg-paraflow-green/10 border border-paraflow-green/20 flex items-center justify-center mb-5 group-hover:scale-110 group-hover:bg-paraflow-green/15 transition-all duration-500">
          {icon}
        </div>
        
        {/* 标题 */}
        <h4 className="text-white text-lg font-medium mb-3 group-hover:text-paraflow-green transition-colors duration-300">
          {title}
        </h4>
        
        {/* 描述 */}
        <p className="text-gray-500 text-sm leading-relaxed">
          {description}
        </p>
      </div>
    </div>
  );
}

export default function Audience() {
  const sectionRef = useRef<HTMLDivElement>(null);

  const audiences: Omit<AudienceCardProps, "index">[] = [
    {
      icon: <Rocket className="w-5 h-5 text-paraflow-green" />,
      title: "AI Start-ups",
      description: "Ship your MVP in days, not months. Iterate on your AI logic and UI interface simultaneously on one canvas.",
    },
    {
      icon: <Building2 className="w-5 h-5 text-paraflow-green" />,
      title: "Design & Dev Agencies",
      description: "Deliver high-fidelity production apps to clients faster. Maintain distinct design systems for every client project.",
    },
    {
      icon: <Target className="w-5 h-5 text-paraflow-green" />,
      title: "Product Managers",
      description: "Turn PRDs into live, testable apps. Verify user flows and business logic without waiting for engineering cycles.",
    },
    {
      icon: <Brain className="w-5 h-5 text-paraflow-green" />,
      title: "Product Designers",
      description: "Design with real functional components. Ensure your vision is pixel-perfect in production, exactly as you designed it.",
    },
    {
      icon: <Code className="w-5 h-5 text-paraflow-green" />,
      title: "Engineers",
      description: "Skip the boilerplate setup. Get clean, modular code generated by the agent and focus on complex backend logic.",
    },
  ];

  return (
    <section ref={sectionRef} className="relative bg-black py-32 overflow-hidden">
      {/* 顶部横向装饰线 - 炫彩渐变 */}
      <div 
        className="absolute top-0 left-0 right-0 h-[0.5px]"
        style={{
          background: "linear-gradient(90deg, transparent 0%, rgba(255, 255, 255, 0.1) 15%, rgba(255, 255, 255, 0.3) 30%, rgba(255, 255, 255, 0.5) 45%, rgba(255, 255, 255, 0.6) 50%, rgba(255, 255, 255, 0.5) 55%, rgba(255, 255, 255, 0.3) 70%, rgba(255, 255, 255, 0.1) 85%, transparent 100%)",
        }}
      />
      
      {/* 星空背景 */}
      <StarBackground starCount={80} opacity={1} />
      
      {/* 渐变光晕 */}
      <div className="absolute inset-0 z-0 pointer-events-none">
        <div 
          className="absolute top-1/2 left-0 -translate-y-1/2 w-[600px] h-[800px]"
          style={{
            background: "radial-gradient(ellipse, rgba(0, 192, 92, 0.06) 0%, transparent 60%)",
            filter: "blur(100px)",
          }}
        />
        <div 
          className="absolute top-1/2 right-0 -translate-y-1/2 w-[600px] h-[800px]"
          style={{
            background: "radial-gradient(ellipse, rgba(121, 242, 0, 0.04) 0%, transparent 60%)",
            filter: "blur(100px)",
          }}
        />
      </div>

      <div className="relative z-10 w-full max-w-[1400px] mx-auto px-6 lg:px-8">
        {/* 区块标题 */}
        <div className="text-center mb-20">
          <h2 className="font-display text-4xl md:text-5xl lg:text-6xl text-white italic leading-tight mb-6">
            Built for every role
          </h2>
          <p className="text-gray-400 text-lg max-w-2xl mx-auto">
            Whether you are building a company or a feature.
          </p>
        </div>

        {/* 用户角色卡片 - 第一行 3 个 */}
        <div className="grid grid-cols-1 md:grid-cols-3 gap-6 mb-6">
          {audiences.slice(0, 3).map((audience, index) => (
            <AudienceCard 
              key={index}
              {...audience}
              index={index}
            />
          ))}
        </div>
        
        {/* 用户角色卡片 - 第二行 2 个居中 */}
        <div className="grid grid-cols-1 md:grid-cols-2 gap-6 max-w-3xl mx-auto">
          {audiences.slice(3).map((audience, index) => (
            <AudienceCard 
              key={index + 3}
              {...audience}
              index={index + 3}
            />
          ))}
        </div>
      </div>
    </section>
  );
}

