"use client";

import { useEffect, useRef, useState } from "react";
import StarBackground from "./StarBackground";
import ConstellationIcon from "./ConstellationIcon";

interface AudienceCardProps {
  iconType: 'rocket' | 'building' | 'flowchart' | 'monitor' | 'code' | 'linechart';
  title: string;
  description: string;
  index: number;
  height?: number;
  titleMaxWidth?: string;
}

// 通用星座卡片组件
function ConstellationCard({ iconType, title, description, index, height = 160, titleMaxWidth }: AudienceCardProps) {
  const cardRef = useRef<HTMLDivElement>(null);
  const [isVisible, setIsVisible] = useState(false);
  const [isHovered, setIsHovered] = useState(false);

  useEffect(() => {
    const observer = new IntersectionObserver(
      ([entry]) => {
        if (entry.isIntersecting) {
          setTimeout(() => setIsVisible(true), index * 100);
        }
      },
      { threshold: 0.2 }
    );

    if (cardRef.current) {
      observer.observe(cardRef.current);
    }

    return () => observer.disconnect();
  }, [index]);

  return (
    <div 
      ref={cardRef}
      className={`group relative ${
        isVisible ? "opacity-100 translate-y-0" : "opacity-0 translate-y-8"
      } transition-all duration-700 ease-out`}
      onMouseEnter={() => setIsHovered(true)}
      onMouseLeave={() => setIsHovered(false)}
    >
      <div 
        className="relative bg-black border border-white/40 rounded-2xl p-6 hover:border-paraflow-green hover:bg-paraflow-green/5 transition-all duration-500 cursor-pointer overflow-hidden"
        style={{ height: `${height}px` }}
      >
        {/* 星座连线效果 - 覆盖整个卡片 */}
        <div className="absolute inset-0 overflow-hidden pointer-events-none">
          <ConstellationIcon
            iconType={iconType}
            isHovered={isHovered}
            staticColor="rgba(255, 255, 255, 0.15)"
            hoverColor="rgba(0, 192, 92, 1)"
          />
        </div>
        
        {/* 左侧文字内容 - 垂直居中 */}
        <div className="relative z-10 flex-1 pr-4 h-full flex flex-col justify-center">
          {/* 标题 - hover 时缩小上移 */}
          <h4 
            className={`text-white font-medium group-hover:text-paraflow-green transition-all duration-500 leading-tight ${
              isHovered ? 'text-xl mt-4' : 'text-2xl mt-[40px]'
            }`}
            style={titleMaxWidth ? { maxWidth: titleMaxWidth } : undefined}
          >
            {title}
          </h4>
          
          {/* 描述 - hover 时显示，两行 */}
          <p className={`text-gray-400 text-sm leading-relaxed mt-2 transition-all duration-500 line-clamp-2 max-w-[420px] ${
            isHovered ? 'opacity-100 translate-y-0' : 'opacity-0 translate-y-3'
          }`}>
            {description}
          </p>
        </div>
      </div>
    </div>
  );
}

export default function Audience() {
  const sectionRef = useRef<HTMLDivElement>(null);

  const audiences: Omit<AudienceCardProps, "index">[] = [
    {
      iconType: "rocket",
      title: "Startup",
      description: "Ship your MVP in days, not months. Iterate on your AI logic and UI interface simultaneously on one canvas.",
      height: 160,
    },
    {
      iconType: "building",
      title: "Design & Develop Studio",
      description: "Deliver high-fidelity production apps to clients faster. Maintain distinct design systems for every client project.",
      height: 160,
    },
    {
      iconType: "flowchart",
      title: "PM",
      description: "Turn PRDs into live, testable apps. Verify user flows and business logic without waiting for engineering cycles.",
      height: 200,
    },
    {
      iconType: "monitor",
      title: "Product Designer",
      description: "Design with real functional components. Ensure your vision is pixel-perfect in production, exactly as you designed it.",
      height: 200,
      titleMaxWidth: "100px",
    },
    {
      iconType: "code",
      title: "Engineer",
      description: "Skip the boilerplate setup. Get clean, modular code generated by the agent and focus on complex backend logic.",
      height: 200,
    },
    {
      iconType: "linechart",
      title: "Marketing & Operation",
      description: "Launch campaign tools and landing pages without blocking engineering. Own your marketing stack from design to data.",
      height: 200,
      titleMaxWidth: "140px",
    },
  ];

  return (
    <section ref={sectionRef} className="relative bg-black py-32 -mt-[30px] overflow-hidden">
      {/* 顶部横向装饰线 */}
      <div 
        className="absolute top-0 left-0 right-0 h-px"
        style={{
          background: 'linear-gradient(90deg, transparent 0%, rgba(255,255,255,0.4) 15%, rgba(255,255,255,0.4) 85%, transparent 100%)',
        }}
      />
      
      {/* 星空背景 */}
      <StarBackground starCount={80} opacity={1} />
      
      {/* 渐变光晕 */}
      <div className="absolute inset-0 z-0 pointer-events-none">
        <div 
          className="absolute top-1/2 left-0 -translate-y-1/2 w-[600px] h-[800px]"
          style={{
            background: "radial-gradient(ellipse, rgba(0, 192, 92, 0.06) 0%, transparent 60%)",
            filter: "blur(100px)",
          }}
        />
        <div 
          className="absolute top-1/2 right-0 -translate-y-1/2 w-[600px] h-[800px]"
          style={{
            background: "radial-gradient(ellipse, rgba(121, 242, 0, 0.04) 0%, transparent 60%)",
            filter: "blur(100px)",
          }}
        />
      </div>

      <div className="relative z-10 w-full max-w-[1400px] mx-auto px-6 lg:px-8">
        {/* 区块标题 */}
        <div className="text-center mb-20">
          <h2 className="font-display text-4xl md:text-5xl lg:text-6xl text-white leading-tight mb-6">
            Built for every role
          </h2>
          <p className="text-white/30 text-lg max-w-2xl mx-auto">
            Whether you are building a company or a feature.
          </p>
        </div>

        {/* 用户角色卡片 - 第一行 2 个 */}
        <div className="grid grid-cols-1 md:grid-cols-2 gap-6 mb-6">
          <ConstellationCard 
            iconType={audiences[0].iconType}
            title={audiences[0].title}
            description={audiences[0].description}
            height={audiences[0].height}
            index={0}
          />
          <ConstellationCard 
            iconType={audiences[1].iconType}
            title={audiences[1].title}
            description={audiences[1].description}
            height={audiences[1].height}
            index={1}
          />
        </div>
        
        {/* 用户角色卡片 - 第二行 4 个 */}
        <div className="grid grid-cols-1 md:grid-cols-4 gap-6">
          <ConstellationCard 
            iconType={audiences[2].iconType}
            title={audiences[2].title}
            description={audiences[2].description}
            height={audiences[2].height}
            index={2}
          />
          <ConstellationCard 
            iconType={audiences[3].iconType}
            title={audiences[3].title}
            description={audiences[3].description}
            height={audiences[3].height}
            titleMaxWidth={audiences[3].titleMaxWidth}
            index={3}
          />
          <ConstellationCard 
            iconType={audiences[4].iconType}
            title={audiences[4].title}
            description={audiences[4].description}
            height={audiences[4].height}
            index={4}
          />
          <ConstellationCard 
            iconType={audiences[5].iconType}
            title={audiences[5].title}
            description={audiences[5].description}
            height={audiences[5].height}
            titleMaxWidth={audiences[5].titleMaxWidth}
            index={5}
          />
        </div>
      </div>
    </section>
  );
}

